### ISSUE TITLE
problem during installation

### ISSUE THREAD

**Issue by dutchjes** [meowcat/fastliclust#1]
When installing from R (3.4.3), I get this error message:

> install_github("meowcat/fastliclust")
Downloading GitHub repo meowcat/fastliclust@master
from URL https://api.github.com/repos/meowcat/fastliclust/zipball/master
Installing fastliclust
"C:/PROGRA~1/R/R-34~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL "C:/Users/uchemadmin/AppData/Local/Temp/Rtmp8OExPN/devtools23dc12522b35/meowcat-fastliclust-101f25f" --library="C:/DATA/Rlib" --install-tests 

* installing *source* package 'fastliclust' ...
** libs

*** arch - i386
C:/RBUILD~1/3.4/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/DATA/Rlib/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBUILD~1/3.4/Rtools/mingw_32/bin/g++  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/DATA/Rlib/Rcpp/include"        -O2 -Wall  -mtune=generic -c fastliclust.cpp -o fastliclust.o
fastliclust.cpp: In function 'void fastLiclust_iter(Rcpp::IntegerMatrix&, Rcpp::NumericVector&, Rcpp::IntegerVector&, int, int&, int&, double)':
fastliclust.cpp:57:7: warning: unused variable 'n' [-Wunused-variable]
   int n = weights.length();
       ^
fastliclust.cpp: In function 'int findMin(Rcpp::NumericVector&, int, int)':
fastliclust.cpp:246:7: warning: unused variable 'n' [-Wunused-variable]
   int n = sim.length();
       ^
C:/RBUILD~1/3.4/Rtools/mingw_32/bin/g++ -shared -s -static-libgcc -o fastliclust.dll tmp.def RcppExports.o fastliclust.o -LC:/PROGRA~1/R/R-34~1.3/bin/i386 -lR
installing to C:/DATA/Rlib/fastliclust/libs/i386

*** arch - x64
C:/RBUILD~1/3.4/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/DATA/Rlib/Rcpp/include"        -O2 -Wall  -mtune=generic -c RcppExports.cpp -o RcppExports.o
C:/RBUILD~1/3.4/Rtools/mingw_64/bin/g++  -I"C:/PROGRA~1/R/R-34~1.3/include" -DNDEBUG  -I"C:/DATA/Rlib/Rcpp/include"        -O2 -Wall  -mtune=generic -c fastliclust.cpp -o fastliclust.o
fastliclust.cpp: In function 'void fastLiclust_iter(Rcpp::IntegerMatrix&, Rcpp::NumericVector&, Rcpp::IntegerVector&, int, int&, int&, double)':
fastliclust.cpp:57:7: warning: unused variable 'n' [-Wunused-variable]
   int n = weights.length();
       ^
fastliclust.cpp: In function 'int findMin(Rcpp::NumericVector&, int, int)':
fastliclust.cpp:246:7: warning: unused variable 'n' [-Wunused-variable]
   int n = sim.length();
       ^
C:/RBUILD~1/3.4/Rtools/mingw_64/bin/g++ -shared -s -static-libgcc -o fastliclust.dll tmp.def RcppExports.o fastliclust.o -LC:/PROGRA~1/R/R-34~1.3/bin/x64 -lR
installing to C:/DATA/Rlib/fastliclust/libs/x64
** R
** inst
** preparing package for lazy loading
Warning: package 'igraph' was built under R version 3.4.4
** help
Warning: C:/Users/uchemadmin/AppData/Local/Temp/Rtmp8OExPN/devtools23dc12522b35/meowcat-fastliclust-101f25f/man/fastliclust-package.Rd:26: All text must be in a section
Warning: C:/Users/uchemadmin/AppData/Local/Temp/Rtmp8OExPN/devtools23dc12522b35/meowcat-fastliclust-101f25f/man/fastliclust-package.Rd:27: All text must be in a section
*** installing help indices
  converting help for package 'fastliclust'
    finding HTML links ... done
    crop                                    html  
Error: C:/Users/uchemadmin/AppData/Local/Temp/Rtmp8OExPN/devtools23dc12522b35/meowcat-fastliclust-101f25f/man/crop.Rd:16: Bad \link text
* removing 'C:/DATA/Rlib/fastliclust'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by meowcat** [comment]
Fixed by eff556d55eae8e983338f9c0010505fbfe86f206
